<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MangaStore.Application</RootNamespace>
    <AssemblyName>MangaStore.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MangaStore.Domain\MangaStore.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

</Project>
